// tools/music-bake/music-data.test.mjs — RED for sw6-1.
//
// Lives WITH the tool as .mjs, mirroring tools/pokey-bake: the bake is build-time
// Node tooling, while the game's TS suite stays browser-pure. Vitest picks it up via
// default **/*.test.mjs discovery. Nothing under tools/music-bake/ exists yet, so
// this file is RED today (valid RED).
//
// ── THE CONTRACT DEV MUST BUILD ──────────────────────────────────────────────
//   music-data.mjs — GENERATED by gen-music-data.mjs from SWMUS.MAC. Carries the
//   LIFTED BYTE STREAMS, nothing more; decoding them is the player's job.
//
//     MUSIC_SOURCE = { file: 'SWMUS.MAC', sha256, generator: 'gen-music-data.mjs' }
//     TRACKS = {
//       space: { segments: [ { tune: 'TH5', tuneIndices: [27,28,29,30],
//                              voices: [ number[], number[], number[], number[] ] }, … ] },
//       towers: …, trench: …, imperialMarch: …,
//     }
//
// ── THE ORACLE IS HAND-TRANSCRIBED, ON PURPOSE ───────────────────────────────
// AC-3 asks that the decoder be pinned against the notes the 1983 author wrote down.
// SWMUS.MAC documents its own encoding — every `.BYTE` carries its macro call as a
// comment directly above it — but SWMUS.MAC is NOT repo content (the 1983 tree is a
// local checkout; reference/ is gitignored). A test that read it would skip in CI
// and protect nothing.
//
// So the oracle below is transcribed BY HAND and lives here, in the repo, as the
// fixed point. If the generator mis-parses SWMUS.MAC, the generated bytes will not
// decode to this transcription and these tests fail. An OPTIONAL cross-check against
// the real SWMUS.MAC runs where the 1983 tree is checked out, which guards the
// transcription itself against my own typos.
// ─────────────────────────────────────────────────────────────────────────────
import { describe, it, expect } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { TRACKS, MUSIC_SOURCE } from './music-data.mjs'
import { decodeVoice, NOTTAB } from './pm-player.mjs'

const here = (rel) => fileURLToPath(new URL(rel, import.meta.url))

// The 1983 Atari "Warp Speed" source tree — a local checkout, not repo content.
const SOURCE_DIR = `${process.env.HOME}/Projects/star-wars-1983-source-text`
const haveSource = existsSync(`${SOURCE_DIR}/SWMUS.MAC`)

// ── The ROM's phase -> tune mapping, taken from the source's own CALLERS ──────
//
// WSMAIN.MAC is the only thing that fires music, and there are exactly 11 `JSR PM*`
// sites in the entire 1983 tree:
//
//   space   $24 PMTH5  WSMAIN:1430  ";THEME MUSIC"                -> TH5V1-4 (27-30)
//           $25 PMTHB  WSMAIN:1435  ";THEME B FOLLOWS MAIN THEME" -> THB1-4  (35-38)
//   towers  $20 PM4TH  WSMAIN:1636  ";BATTLE MUSIC IN FOURTHS"    -> SW4V1-4 (31-34)
//           $21 PMREB  WSMAIN:1673  ";FINISH GROUND WITH REBEL"   -> REBV1-4 (19-22)
//   trench  $22 PMRRP  WSMAIN:1865  ";THEN DO REBEL REPEAT THEME" -> RR1-4   (23-26)
//   vader   $1D PMDAR  WSMAIN:1426  ";THEN DO DARTH THEME"        -> DARV1-4 (43-46)
//
// ⚠ PMBEN IS NOT THE TOWERS THEME. SNDPM.MAC:337 labels it ";BENS THEME (START OF
// TOWER)", and the sw6-1 story and its design spec both trusted that comment — but
// it is STALE. PMBEN's only caller in the whole source is WSMAIN.MAC:2161:
//
//     JSR PMBEN      ;BEN'S THEME WHEN LOSE GAME WITH NO HIGH SCORE
//
// It is the GAME-OVER theme. Baking it into towers_theme.wav would play the
// you-lost music over the Death Star surface. The mapping below follows the
// callers, not the label. Do not "fix" this back.
const ROM_MAPPING = {
  space: ['TH5', 'THB'],
  towers: ['SW4', 'REB'],
  trench: ['RR'],
  imperialMarch: ['DAR'],
}

const ROM_TUNE_INDICES = {
  space: [
    [27, 28, 29, 30],
    [35, 36, 37, 38],
  ],
  towers: [
    [31, 32, 33, 34],
    [19, 20, 21, 22],
  ],
  trench: [[23, 24, 25, 26]],
  imperialMarch: [[43, 44, 45, 46]],
}

// ── AC-3 ORACLE: RR1 (trench, voice 1), hand-transcribed from SWMUS.MAC:2034 ──
//
// The source, verbatim (each macro call sits as a comment above its bytes):
//
//   RR1:  ;.NRATE 152.   .BYTE 80, 152.
//         ;.AENV  3      .BYTE 87, 3
//         ;.NOTE  F5C    .BYTE 042, 016
//         ;.LOOP  2      .BYTE 8E, 2
//         ;.NOTE  F5H,D5E,R1E,D5C,D5C,D5D
//                        .BYTE 042,080 / 03f,020 / 00,020 / 03f,016 / 03f,016 / 03f,014
//         ;.ENDL         .BYTE 8F, 0
//         ;.NOTE  AF5H,G5Q,G5C,AF5C,G5D
//                        .BYTE 045,080 / 044,040 / 044,016 / 045,016 / 044,014
//         ;.NOTE  F5Q,D5H.T,D5HT
//                        .BYTE 042,040 / 03f,0c0 / 03f,081
//         ;.NOTE  D5E,R1E,R1C,R1C
//                        .BYTE 03f,021 / 00,020 / 00,016 / 00,016
//         ;.NOTE  F5D    .BYTE 042, 014
//
// Pitch byte = octave*12 + semitone + 1; 0 = REST (NOTTAB[0] is `.WORD 0 ;REST`):
//   F5 = 5*12+5+1 = 0x42    D5 = 5*12+2+1 = 0x3f
//   G5 = 5*12+7+1 = 0x44    AF5 = G#5 = 5*12+8+1 = 0x45
//
// `.LOOP 2` plays its body TWICE in total (SNDPM.MAC PKSL/PKEL: store N, then
// `DEC VLC / LBEQ done`).
const RR1_ORACLE = [
  [0x42, 0x16], // F5C

  [0x42, 0x80], // .LOOP 2 body, pass 1:  F5H
  [0x3f, 0x20], //                        D5E
  [0x00, 0x20], //                        R1E  <- a REST. 0 is falsy; it must survive.
  [0x3f, 0x16], //                        D5C
  [0x3f, 0x16], //                        D5C
  [0x3f, 0x14], //                        D5D

  [0x42, 0x80], // .LOOP 2 body, pass 2:  F5H
  [0x3f, 0x20], //                        D5E
  [0x00, 0x20], //                        R1E
  [0x3f, 0x16], //                        D5C
  [0x3f, 0x16], //                        D5C
  [0x3f, 0x14], //                        D5D
  // .ENDL

  [0x45, 0x80], // AF5H
  [0x44, 0x40], // G5Q
  [0x44, 0x16], // G5C
  [0x45, 0x16], // AF5C
  [0x44, 0x14], // G5D

  [0x42, 0x40], // F5Q
  [0x3f, 0xc0], // D5H.T
  [0x3f, 0x81], // D5HT

  [0x3f, 0x21], // D5E
  [0x00, 0x20], // R1E
  [0x00, 0x16], // R1C
  [0x00, 0x16], // R1C

  [0x42, 0x14], // F5D
]

// ── AC-3 ORACLE #2: SW4V1 (towers, voice 1), hand-transcribed from SWMUS.MAC:2515 ──
//
// RR1 (above) is a straight tune: it never transposes. SW4V1 is the one that does, and
// it is also the voice whose PHASE MAPPING this story originally got wrong — so the
// riskiest voice in the corpus had the least coverage. Its `.CKEY -12.` sits INSIDE the
// `.LOOP 2`, so the key COMPOUNDS across the two passes (0, then −12, ending at −24)
// before `.NKEY 0` puts it back. Nothing else in the corpus exercises that.
//
//   SW4V1:  ;.NRATE 96.    .BYTE 80, 96.
//           ;.AENV  1      .BYTE 87, 1
//           ;.NVOL  MP     .BYTE 82, 5
//           ;.CVOL  1      .BYTE 83, 1
//           ;.LOOP  2      .BYTE 8E, 2
//           ;.NOTE  G5C,G5C,G5DT,G5C,G5C,G5D,AF5C,AF5C,AF5D,BF5C,BF5C,BF5D
//                          .BYTE 044,016 / 044,016 / 044,014 / 044,017 / 044,016 / 044,014
//                                045,016 / 045,016 / 045,014 / 047,016 / 047,016 / 047,014
//           ;.CKEY  -12.   .BYTE 85, -12.      <- DECIMAL (the trailing dot). Hex would be −18.
//           ;.ENDL         .BYTE 8F, 0
//           ;.NKEY  0      .BYTE 84, 0         <- undoes the compounded −24
//           ;.NVOL  M      .BYTE 82, 7
//           ;.AENV  3      .BYTE 87, 3
//           ;.NOTE  R1H,R1H          .BYTE 00,080 / 00,080
//           ;.NOTE  R1H,R1E,D5E,G5E,C6E
//                          .BYTE 00,080 / 00,020 / 03f,020 / 044,020 / 049,020
//
// Pitch byte = octave*12 + semitone + 1:
//   G5 = 0x44   AF5 (G#5) = 0x45   BF5 (A#5) = 0x47   C6 = 0x49   D5 = 0x3f
// Transposed down a twelfth: G5 -> 0x38, AF5 -> 0x39, BF5 -> 0x3b.
const G5 = 0x44
const AF5 = 0x45
const BF5 = 0x47
const C6 = 0x49
const D5 = 0x3f
const REST = 0x00
const down12 = (n) => n - 12

const SW4V1_ORACLE = [
  // .LOOP 2, pass 1 — key 0, so the notes sound exactly as written
  [G5, 0x16], [G5, 0x16], [G5, 0x14], [G5, 0x17], [G5, 0x16], [G5, 0x14],
  [AF5, 0x16], [AF5, 0x16], [AF5, 0x14],
  [BF5, 0x16], [BF5, 0x16], [BF5, 0x14],
  // .CKEY -12  -> key = -12

  // .LOOP 2, pass 2 — the SAME bytes, sounding an octave lower
  [down12(G5), 0x16], [down12(G5), 0x16], [down12(G5), 0x14],
  [down12(G5), 0x17], [down12(G5), 0x16], [down12(G5), 0x14],
  [down12(AF5), 0x16], [down12(AF5), 0x16], [down12(AF5), 0x14],
  [down12(BF5), 0x16], [down12(BF5), 0x16], [down12(BF5), 0x14],
  // .CKEY -12 again -> key = -24, and .ENDL exits

  // .NKEY 0 — the key is RESET, so these sound absolute again. If .NKEY were treated
  // as relative (or ignored), every note below would come out 24 semitones flat, and
  // two of them would fall clean off the bottom of NOTTAB.
  [REST, 0x80], [REST, 0x80], [REST, 0x80], [REST, 0x20],
  [D5, 0x20], [G5, 0x20], [C6, 0x20],
]

const trackNames = () => Object.keys(TRACKS)
const segmentsOf = (t) => TRACKS[t].segments
const allVoices = () => trackNames().flatMap((t) => segmentsOf(t).flatMap((s) => s.voices))

describe('sw6-1 AC-1 — PROVENANCE: the tune data is GENERATED from SWMUS.MAC', () => {
  // The story says "mirror tools/speech-bake/gen-speech-data.mjs". That file does not
  // exist: speech-data.mjs's header credits a generator that was never committed. The
  // exemplar therefore cannot be mirrored literally — and mirroring it literally is
  // precisely the sin (a data module nobody can reproduce). The generator must SHIP.
  it('ships the generator that writes the data module', () => {
    expect(existsSync(here('./gen-music-data.mjs'))).toBe(true)
  })

  it('declares its provenance: generated from SWMUS.MAC, not hand-edited', () => {
    expect(MUSIC_SOURCE.file).toMatch(/SWMUS\.MAC/i)
    expect(MUSIC_SOURCE.generator).toMatch(/gen-music-data\.mjs/)

    const header = readFileSync(here('./music-data.mjs'), 'utf8').slice(0, 2000)
    expect(header).toMatch(/GENERATED/i)
    expect(header).toMatch(/do not hand-edit/i)
  })

  it('records the checksum of the exact SWMUS.MAC it was generated from', () => {
    // Provenance you can audit without the 1983 tree in hand.
    expect(MUSIC_SOURCE.sha256).toMatch(/^[0-9a-f]{64}$/)
  })

  it('does NOT source the data from the disassembly', () => {
    // The story is explicit: do not reverse-engineer Music_Functions.asm's
    // `fdb $805A, $8701, $3316` note words. Read the original source instead.
    const gen = readFileSync(here('./gen-music-data.mjs'), 'utf8')
    expect(gen).toMatch(/SWMUS\.MAC/)
    expect(gen).not.toMatch(/Music_Tables\.asm|Music_Functions\.asm/)
  })
})

describe('sw6-1 AC-5 — PHASE -> TUNE mapping, pinned so it cannot silently drift', () => {
  it('carries exactly the four tracks the MUSIC manifest names', () => {
    expect(trackNames().sort()).toEqual(['imperialMarch', 'space', 'towers', 'trench'])
  })

  it('maps each track to the tunes the ROM CALLERS fire', () => {
    for (const [track, tunes] of Object.entries(ROM_MAPPING)) {
      expect(segmentsOf(track).map((s) => s.tune)).toEqual(tunes)
    }
  })

  it('REFUTES towers = PMBEN — that is the game-over theme, not the surface theme', () => {
    const towerTunes = segmentsOf('towers').map((s) => s.tune)
    expect(towerTunes).not.toContain('BEN')
    expect(towerTunes).toContain('SW4') // PM4TH — ";BATTLE MUSIC IN FOURTHS: GROUND TOWERS"
  })

  it('gives every tune the four POKEY voices the ROM allocates it', () => {
    // Each PM* entry point issues exactly four `.TUNE voice,index` calls.
    for (const track of trackNames())
      for (const seg of segmentsOf(track)) expect(seg.voices).toHaveLength(4)
  })
})

describe('sw6-1 AC-6 — SEGMENTS: one flattened loop per phase, in ROM order', () => {
  // DECISION (evidence in the session file): the cabinet plays a SEQUENCE per phase —
  // space = TH5 then THB; towers = 4TH then REB — but our engine's contract (sw3-5) is
  // ONE looping track per phase on a single music channel, with no notion of a timed
  // one-shot follow-on. So each phase is baked as one flattened loop: its segments
  // concatenated in the order WSMAIN fires them. The manifest stays at four files and
  // no ROM segment is dropped.
  it('gives space two segments — the main theme, then theme B', () => {
    expect(segmentsOf('space').map((s) => s.tune)).toEqual(['TH5', 'THB'])
  })

  it('gives towers two segments — battle in fourths, then the rebel finish', () => {
    expect(segmentsOf('towers').map((s) => s.tune)).toEqual(['SW4', 'REB'])
  })

  it('gives trench and the Imperial March a single segment each', () => {
    expect(segmentsOf('trench')).toHaveLength(1)
    expect(segmentsOf('imperialMarch')).toHaveLength(1)
  })
})

describe('sw6-1 AC-3 — ORACLE: the bytes decode to the notes the 1983 author wrote', () => {
  it('reproduces RR1 (trench, voice 1) note-for-note, including the LOOP expansion', () => {
    // The whole story in one assertion. If the generator drops a rest, misreads the
    // radix, or expands `.LOOP 2` as anything but "body twice", this diverges from
    // what the author wrote in his own comments.
    const rr1 = decodeVoice(TRACKS.trench.segments[0].voices[0])
    const got = rr1.notes.slice(0, RR1_ORACLE.length).map((n) => [n.note, n.duration])
    expect(got).toEqual(RR1_ORACLE)
  })

  it('reproduces SW4V1 (towers, voice 1) — the COMPOUNDING transposition, note-for-note', () => {
    // The riskiest voice in the corpus: the only one that transposes, compounding
    // `.CKEY -12` inside a `.LOOP 2` and then resetting with `.NKEY 0`. Get the loop
    // wrong and pass 2 sounds in the wrong octave; get `.NKEY` wrong and the tail is
    // 24 semitones flat; read `-12.` as hex and every transposed note is a tritone out.
    const sw4v1 = decodeVoice(TRACKS.towers.segments[0].voices[0])
    const got = sw4v1.notes.slice(0, SW4V1_ORACLE.length).map((n) => [n.note, n.duration])
    expect(got).toEqual(SW4V1_ORACLE)
  })

  it('reads SW4V1 .CKEY -12. as DECIMAL — the hex reading transposes by a tritone', () => {
    // The radix trap on the transposition itself. `.BYTE 85, -12.` carries the trailing
    // dot, so it is decimal 12. Read as hex it is 18 — an octave and a tritone — and
    // the second pass of the loop would still be *music*, just in the wrong key.
    const sw4v1 = decodeVoice(TRACKS.towers.segments[0].voices[0])
    const pass2 = sw4v1.notes[12] // first note of the loop's second pass
    expect(pass2.note).toBe(G5 - 12) // 0x38
    expect(pass2.note).not.toBe(G5 - 0x12) // 0x32 — the hex misreading
  })

  it('holds the volume the author set: .NVOL 5 then .CVOL +1, and .NVOL 7 after the loop', () => {
    // `.CVOL` is signed, and the loop's notes sit a step above the opening volume.
    const sw4v1 = decodeVoice(TRACKS.towers.segments[0].voices[0])
    expect(sw4v1.notes[0].volume).toBe(6) // NVOL 5, CVOL +1
    expect(sw4v1.notes[24].volume).toBe(7) // NVOL 7, after .ENDL
  })

  it('opens the trench voice at the tempo the author set: .NRATE 152 (DECIMAL)', () => {
    const rr1 = decodeVoice(TRACKS.trench.segments[0].voices[0])
    expect(rr1.tempo).toBe(152)
    // Refute the hex reading: 0x152 = 338 is not merely a different tempo, it could
    // not even fit in the single byte the assembler emitted.
    expect(rr1.tempo).not.toBe(0x152)
    expect(rr1.tempo).toBeLessThanOrEqual(0xff)
  })

  it('keeps rests as real events — a rest is note 0 held for a duration', () => {
    // lang-review JS #4: `if (note)` silently drops every rest, and these tunes are
    // full of them.
    const rr1 = decodeVoice(TRACKS.trench.segments[0].voices[0])
    const rests = rr1.notes.filter((n) => n.note === 0)
    expect(rests.length).toBeGreaterThan(0)
    for (const r of rests) expect(r.duration).toBeGreaterThan(0)
  })

  it('never emits a pitch that collides with the opcode space', () => {
    // The player tells a note from a function by the sign bit (SNDPM.MAC:701,
    // `TSTB ;CHECK THE OPCODE(FIRST BYTE)`). Every pitch must stay below 0x80 or the
    // stream is ambiguous.
    for (const voice of allVoices())
      for (const { note } of decodeVoice(voice).notes) expect(note).toBeLessThan(0x80)
  })

  it('sounds every note in the corpus ON the table — nothing quietly becomes a rest', () => {
    // The player now THROWS on a note that falls off NOTTAB, so this asserts the
    // margin exists rather than trusting it. Every effective (transposed) note in all
    // 24 voices must be a real entry, and every non-rest must have a real divisor —
    // otherwise it would sound as silence and the tune would still "work".
    const effective = allVoices().flatMap((v) => decodeVoice(v).notes.map((n) => n.note))

    for (const note of effective) {
      expect(note).toBeGreaterThanOrEqual(0)
      expect(note).toBeLessThan(NOTTAB.length)
      if (note !== 0) expect(NOTTAB[note]).toBeGreaterThan(0)
    }

    // and the margin, stated out loud: the corpus lives well inside the table (C2..C6).
    const sounded = effective.filter((n) => n !== 0)
    expect(Math.min(...sounded)).toBe(25)
    expect(Math.max(...sounded)).toBe(73)
  })

  it('gives every one of the 24 voices real music, terminated properly', () => {
    const voices = allVoices()
    expect(voices).toHaveLength(24) // 6 tunes x 4 voices
    for (const voice of voices) {
      expect(voice.length).toBeGreaterThan(2) // more than a bare terminator
      expect(decodeVoice(voice).notes.length).toBeGreaterThan(0)
    }
  })
})

describe('sw6-1 AC-4 — RADIX TRAP: refute the wrong reading, do not merely assert the right one', () => {
  it('reads the note stream as HEX, refuting decimal', () => {
    // A decimal reading of the stream is not just wrong, it is largely impossible —
    // the listing is full of letter-bearing operands (`8E`, `0c0`, `03f`). The
    // ALL-DIGIT operands are the trap: they parse either way and quietly differ.
    // RR1 opens `.BYTE 042, 016` = F5 held 0x16 = 22 ticks.
    const rr1 = decodeVoice(TRACKS.trench.segments[0].voices[0])
    expect(rr1.notes[0].note).toBe(0x42)
    expect(rr1.notes[0].duration).toBe(0x16)

    // Refute decimal: 042 -> 42 is F#3, an octave and a half low; 016 -> 16 is a
    // different note length. Both are plausible. Both are wrong.
    expect(rr1.notes[0].note).not.toBe(42)
    expect(rr1.notes[0].duration).not.toBe(16)
  })

  it('reads tune INDICES as decimal — the hex reading scatters a theme across three tunes', () => {
    // The inverse trap, and the nastier one, because it silently yields *music*.
    // SNDPM.MAC's .TUNE macro expands to
    //     LDB #<2*'TNUM'.>        (SNDPM.MAC:325)
    // — the trailing dot forces DECIMAL, and the x2 is the word-offset into TUNTAB.
    // PMTH5 issues `.TUNE 1,27 … 4,30`.
    //
    //   decimal: TUNTAB[27..30] = TH5V1..TH5V4      — one coherent tune.
    //   hex:     TUNTAB[0x27,0x28,0x29,0x30] = [39,40,41,48]
    //            = DESV1, DESV2, DESV3, TSTV2       — three voices of the DESCENT
    //              tune plus a TEST tone. Incoherent, and it would still play.
    for (const [track, expected] of Object.entries(ROM_TUNE_INDICES)) {
      expect(segmentsOf(track).map((s) => s.tuneIndices)).toEqual(expected)
    }

    // and explicitly refute the hex misreading of the main theme
    expect(segmentsOf('space')[0].tuneIndices).not.toEqual([0x27, 0x28, 0x29, 0x30])
  })
})

// ── Optional guard on the hand transcription itself ───────────────────────────
// Runs only where the 1983 tree is checked out (so: not in CI). It proves the oracle
// above was transcribed faithfully, so a typo in MY transcription cannot quietly
// become the spec.
describe.skipIf(!haveSource)('sw6-1 — cross-check the hand-transcribed oracle against the 1983 source', () => {
  it('finds RR1 in SWMUS.MAC carrying the bytes the oracle claims', () => {
    const src = readFileSync(`${SOURCE_DIR}/SWMUS.MAC`, 'latin1').replace(/\r/g, '\n').split('\n')
    const at = src.findIndex((l) => /^RR1:/.test(l))
    expect(at).toBeGreaterThan(-1)

    const window = src.slice(at, at + 12).join('\n')
    expect(window).toMatch(/\.BYTE\s+80,\s*152\./) // .NRATE 152 — DECIMAL, note the dot
    expect(window).toMatch(/\.BYTE\s+87,\s*3/) //     .AENV 3 (QKR)
    expect(window).toMatch(/\.BYTE\s+042,\s*016/) //  .NOTE F5C
    expect(window).toMatch(/\.BYTE\s+8E,\s*2/) //     .LOOP 2
    expect(window).toMatch(/;\s*\.NOTE\s+F5C/) //     the author's own notation
  })

  it("confirms PMBEN's only caller is the game-over path, not the towers phase", () => {
    const text = readFileSync(`${SOURCE_DIR}/WSMAIN.MAC`, 'latin1').replace(/\r/g, '\n')
    const callers = text.split('\n').filter((l) => /JSR\s+PMBEN/.test(l))
    expect(callers).toHaveLength(1)
    expect(callers[0]).toMatch(/LOSE GAME WITH NO HIGH SCORE/i)
  })

  it('confirms PM4TH is fired in the ground/towers phase', () => {
    const text = readFileSync(`${SOURCE_DIR}/WSMAIN.MAC`, 'latin1').replace(/\r/g, '\n')
    const callers = text.split('\n').filter((l) => /JSR\s+PM4TH/.test(l))
    expect(callers).toHaveLength(1)
    expect(callers[0]).toMatch(/BATTLE MUSIC IN FOURTHS/i)
  })
})
