// tools/music-bake/tune-data.test.mjs — RED for sw7-8 (U-010..U-014).
//
// sw6-1 baked the four LOOPING phase tracks. The audit found five ONE-SHOT
// tunes still missing, each with exactly one caller in the 1983 tree — the
// caller, never the entry-point label, names the moment (the PMBEN lesson,
// music-data.test.mjs):
//
//   tune        SNDPM entry      caller                                    ours
//   ---------------------------------------------------------------------------
//   SF2 (1-4)   PMSF2 :330       WSGUNS.MAC:1220 ";SOUND THE DEATH KNELL"  deathKnell
//   BEN (7-10)  PMBEN :337       WSMAIN.MAC:2161 ";BEN'S THEME WHEN LOSE   bensTheme
//                                GAME WITH NO HIGH SCORE"
//   CNT (11-14) PMCNT :344       WSMAIN.MAC:1164 ";CANTINA MUSIC" (PHIENT, cantina
//                                the enter-initials screen)
//   END (15-18) PMEND :351       WSMAIN.MAC:2179 ";START END OF DETH STAR  finale
//                                MUSIC" (PHIDX1, the explosion)
//   DES (39-42) PMDES :393       WSMAIN.MAC:1439 (space PH.TIM 400, the    descent
//                                descend-to-surface flip)
//
// TUNTAB (SWMUS.MAC:22-34) names the voices: SF2V1-4 / BENV1-4 / CNTV1-4 /
// ENDV1-4 / DESV1-4. (TUNTAB entries 5-6, SF2V5/SF2V6, are SUBROUTINES — see
// below — reached only via `.CALL`, never via a `.TUNE`; they are data for the
// knell's voices, not voices of their own.)
//
// ── THE CONTRACT DEV MUST BUILD ──────────────────────────────────────────────
//   music-data.mjs additionally exports TUNES — same shape as TRACKS, one
//   segment per tune — GENERATED by gen-music-data.mjs (which today ERRORS on
//   these streams; see below):
//
//     TUNES = {
//       deathKnell: { segments: [ { tune: 'SF2', tuneIndices: [1,2,3,4],
//                                   voiceLabels: [...], voices: [4 × number[]] } ] },
//       bensTheme: …, cantina: …, finale: …, descent: …,
//     }
//
//   Keeping the TRACKS segment shape means bake-music's voice walker and
//   pm-player serve both; the five .wav files land beside the four tracks
//   under the music/ R2 prefix (tests/shell/tune-channel.test.ts names them).
//
// ── WHY THIS IS A REAL PIPELINE STORY, NOT A CONFIG STORY ────────────────────
// The five streams use opcodes the shipped corpus never touched, so BOTH ends
// of the pipeline must grow:
//
//   0x8D  .CALL n    — call TUNTAB[n] as a subroutine. SF2V1-4 are each
//                      "CALL 6 (setup: NVOL/NRATE/SYN/VC), CKEY k, CALL 5
//                      (the 30-pass loop)". Flattening resolves them.
//   0x90  .GOSUB adr — 3-BYTE record (opcode + address WORD): breaks the
//                      2-byte pair walk. CNTV1 gosubs CSUB1 twice.
//   0x91  .RETURN    — 1-BYTE record, same problem.
//   0x8A  .VC / 0x8C .SYN / 0x81 .CRATE — knell setup + per-pass accelerando.
//
// gen-music-data.mjs currently THROWS on address-operand labels ("are not
// supported. Resolve the label or drop the tune from scope") and pm-player
// THROWS on unimplemented opcodes (by design — a skipped opcode costs a voice
// its stream). Whether Dev flattens at generation time or teaches the player
// call/gosub semantics is Dev's choice: the oracles below pin the DECODED
// note stream (what the cabinet played), seam-agnostically.
//
// ── ORACLES ARE HAND-TRANSCRIBED, ON PURPOSE (sw6-1 idiom) ───────────────────
// SWMUS.MAC is not repo content; each `.BYTE` carries its macro call as a
// comment. The transcriptions below are the in-repo fixed point; the radix
// rules are SWMUS's own (.RADIX 16 with a trailing dot forcing DECIMAL — and
// BOTH misreadings are refuted inline below).
import { describe, it, expect } from 'vitest'

import { TUNES, TRACKS } from './music-data.mjs'
import { decodeVoice } from './pm-player.mjs'

// ── The ROM mapping, from TUNTAB + the .TUNE indices + the callers ───────────
const TUNE_ROM = {
  deathKnell: { tune: 'SF2', tuneIndices: [1, 2, 3, 4], voiceLabels: ['SF2V1', 'SF2V2', 'SF2V3', 'SF2V4'] },
  bensTheme: { tune: 'BEN', tuneIndices: [7, 8, 9, 10], voiceLabels: ['BENV1', 'BENV2', 'BENV3', 'BENV4'] },
  cantina: { tune: 'CNT', tuneIndices: [11, 12, 13, 14], voiceLabels: ['CNTV1', 'CNTV2', 'CNTV3', 'CNTV4'] },
  finale: { tune: 'END', tuneIndices: [15, 16, 17, 18], voiceLabels: ['ENDV1', 'ENDV2', 'ENDV3', 'ENDV4'] },
  descent: { tune: 'DES', tuneIndices: [39, 40, 41, 42], voiceLabels: ['DESV1', 'DESV2', 'DESV3', 'DESV4'] },
}

const tuneNames = () => Object.keys(TUNES)
const segOf = (name) => TUNES[name].segments[0]

describe('sw7-8 — the TUNES catalogue exists and is exactly the five', () => {
  it('exports the five one-shot tunes, and only them', () => {
    expect(tuneNames().sort()).toEqual(['bensTheme', 'cantina', 'deathKnell', 'descent', 'finale'])
  })

  it('keeps the four looping TRACKS untouched (sw6-1 is not re-litigated)', () => {
    expect(Object.keys(TRACKS).sort()).toEqual(['imperialMarch', 'space', 'towers', 'trench'])
  })

  it('each tune is one segment with the ROM tune name, TUNTAB indices, and voice labels', () => {
    for (const [name, rom] of Object.entries(TUNE_ROM)) {
      expect(TUNES[name].segments, `${name} segments`).toHaveLength(1)
      const seg = segOf(name)
      expect(seg.tune, name).toBe(rom.tune)
      expect(seg.tuneIndices, name).toEqual(rom.tuneIndices)
      expect(seg.voiceLabels, name).toEqual(rom.voiceLabels)
    }
  })

  it('every tune carries four raw voice streams, each properly terminated', () => {
    for (const name of Object.keys(TUNE_ROM)) {
      const seg = segOf(name)
      expect(seg.voices, name).toHaveLength(4)
      for (const v of seg.voices) {
        expect(v.length, `${name} voice length`).toBeGreaterThan(2)
        expect(v.length % 2, `${name} voices are (byte, byte) pairs`).toBe(0)
        // End-of-tune terminator: a 0 note with 0 duration (SNDPM's ENDT).
        expect(v.slice(-2), `${name} terminator`).toEqual([0, 0])
      }
    }
  })
})

// ── ORACLE 1: the death knell — CALL flattening + the descending scale ───────
//
//   SF2V1: ;.CALL 6   (SF2V6: .NKEY 0, .NVOL FFF, .NRATE 0CF, .SYN ON,
//                      .VC 0A0, .AENV 0 — setup only, no notes)
//          ;.CKEY 0
//          ;.CALL 5   (SF2V5: .LOOP 30 [ .NOTE E5XT ; .CKEY -1 ; .CRATE 1 ] .ENDL)
//          ;.ENDT
//
// E5 = 5*12 + 4 + 1 = 0x41. The loop body plays ONE note then drops the key a
// semitone and bumps the rate, so the DECODED stream is 30 notes descending
// chromatically from E5 — the death knell is a falling, accelerating scale.
// The other voices are the same scale seeded a cluster apart:
// .CKEY 0 / -1 / -3 / -6 (SWMUS.MAC SF2V1-4).
describe('sw7-8 — ORACLE: the death knell (SF2) — .CALL subroutines flatten to the falling scale', () => {
  const E5 = 0x41

  it('voice 1 decodes to 30 notes, chromatically descending from E5, all one duration', () => {
    const v1 = decodeVoice(segOf('deathKnell').voices[0])
    const notes = v1.notes.map((n) => n.note)
    expect(notes).toHaveLength(30)
    expect(notes[0]).toBe(E5)
    for (let i = 1; i < notes.length; i++) {
      expect(notes[i], `pass ${i + 1}`).toBe(E5 - i) // .CKEY -1 compounds per pass
    }
    for (const n of v1.notes) expect(n.duration).toBe(0x04) // .NOTE E5XT
  })

  it('the four voices open a widening cluster: CKEY 0 / -1 / -3 / -6', () => {
    const firsts = segOf('deathKnell').voices.map((v) => decodeVoice(v).notes[0].note)
    expect(firsts).toEqual([E5, E5 - 1, E5 - 3, E5 - 6])
  })

  it("the knell's tempo comes from the CALLED setup — .NRATE 0CF is HEX 207", () => {
    // The radix trap cuts both ways (SWMUS gotcha): '0CF' carries no dot, so it
    // is ambient-hex 207 — a decimal misreading cannot even parse it, and a
    // generator that silently dropped the .CALL 6 setup would leave the
    // default rate instead. 207 or the flattening is wrong.
    expect(decodeVoice(segOf('deathKnell').voices[0]).tempo).toBe(0xcf)
  })
})

// ── ORACLE 2: Ben's theme — a straight stream, and the DOTTED-decimal tempo ──
//
//   BENV1: ;.NRATE 84.   ;.AENV 2
//          ;.NOTE D4E.,D4S            033,031 / 033,010
//          ;.NOTE G4H,A4QT,A4C,BF4C,C5D
//                                     038,080 / 03a,040 / 03a,017 / 03b,016 / 03d,014
//          ;.NOTE BF4H,D4Q,R1E,D4E    03b,080 / 033,040 / 00,020 / 033,020
//          ;.NOTE G4Q.,A4E,BF4E,…     038,060 / 03a,020 / 03b,020 …
describe("sw7-8 — ORACLE: Ben's theme (BEN) — the game-over consolation, note-for-note", () => {
  const BENV1_ORACLE = [
    [0x33, 0x31], // D4E.
    [0x33, 0x10], // D4S
    [0x38, 0x80], // G4H
    [0x3a, 0x40], // A4QT
    [0x3a, 0x17], // A4C
    [0x3b, 0x16], // BF4C
    [0x3d, 0x14], // C5D
    [0x3b, 0x80], // BF4H
    [0x33, 0x40], // D4Q
    [0x00, 0x20], // R1E — a REST; 0 is falsy and must survive
    [0x33, 0x20], // D4E
    [0x38, 0x60], // G4Q.
    [0x3a, 0x20], // A4E
    [0x3b, 0x20], // BF4E
  ]

  it('voice 1 opens exactly as the 1983 author wrote it', () => {
    const v1 = decodeVoice(segOf('bensTheme').voices[0])
    const got = v1.notes.slice(0, BENV1_ORACLE.length).map((n) => [n.note, n.duration])
    expect(got).toEqual(BENV1_ORACLE)
  })

  it('.NRATE 84. is DECIMAL 84 — the dot is load-bearing', () => {
    const v1 = decodeVoice(segOf('bensTheme').voices[0])
    expect(v1.tempo).toBe(84)
    expect(v1.tempo).not.toBe(0x84) // 132 — the hex misreading
  })
})

// ── ORACLE 3: the cantina — .GOSUB/.RETURN flatten in place ──────────────────
//
//   CNTV1: ;.NRATE 150.  ;.AENV 1  ;.NVOL P
//          .GOSUB CSUB1              <- 0x90 + ADDRESS WORD, then 0x91 RETURN
//          3$: ;.NOTE A4E,GS4E,A4E,GN4E,R1E,FS4E,G4E,FS4E
//          4$: ;.NOTE F4Q.,D4ET,D4H
//          .GOSUB CSUB1              <- again
//          7$: …
//
//   CSUB1: ;.NOTE A4Q,D5Q,A4Q,D5Q    03a,040 / 03f,040 / 03a,040 / 03f,040
//          ;.NOTE A4ET,D5Q,A4E,R1E,GS4E,A4Q
//                                    03a,020 / 03f,041 / 03a,020 / 00,020 / 039,020 / 03a,040
//          .RETURN
describe('sw7-8 — ORACLE: the cantina (CNT) — the hi-score screen, GOSUBs inlined', () => {
  const CSUB1 = [
    [0x3a, 0x40], // A4Q
    [0x3f, 0x40], // D5Q
    [0x3a, 0x40], // A4Q
    [0x3f, 0x40], // D5Q
    [0x3a, 0x20], // A4ET
    [0x3f, 0x41], // D5Q (tied)
    [0x3a, 0x20], // A4E
    [0x00, 0x20], // R1E
    [0x39, 0x20], // GS4E
    [0x3a, 0x40], // A4Q
  ]
  const MELODY_3 = [
    [0x3a, 0x20], // A4E
    [0x39, 0x20], // GS4E
    [0x3a, 0x20], // A4E
    [0x38, 0x20], // GN4E
    [0x00, 0x20], // R1E
    [0x37, 0x20], // FS4E
    [0x38, 0x20], // G4E
    [0x37, 0x20], // FS4E
  ]
  const MELODY_4 = [
    [0x36, 0x60], // F4Q.
    [0x33, 0x20], // D4ET
    [0x33, 0x81], // D4H (tied)
  ]
  const CNTV1_ORACLE = [...CSUB1, ...MELODY_3, ...MELODY_4]

  it('voice 1 decodes to CSUB1, then the bar-3 melody — the gosub ran, then RETURNED', () => {
    const v1 = decodeVoice(segOf('cantina').voices[0])
    const got = v1.notes.slice(0, CNTV1_ORACLE.length).map((n) => [n.note, n.duration])
    expect(got).toEqual(CNTV1_ORACLE)
  })

  it('the riff comes back — CSUB1 plays again after the first melody (the SECOND gosub)', () => {
    const v1 = decodeVoice(segOf('cantina').voices[0])
    const pairs = v1.notes.map((n) => [n.note, n.duration])
    const after = pairs.slice(CNTV1_ORACLE.length, CNTV1_ORACLE.length + CSUB1.length)
    expect(after).toEqual(CSUB1)
  })

  it('.NRATE 150. is decimal — the cantina swings at 150', () => {
    expect(decodeVoice(segOf('cantina').voices[0]).tempo).toBe(150)
  })
})

// ── ORACLE 4: the finale — .NKEY 12. transposes notes but NEVER rests ─────────
//
//   ENDV1: ;.NRATE 128.  ;.AENV 2  ;.NKEY 12.  ;.NVOL MP
//          ;.NOTE R1H                00,080
//          ;.NOTE GF6E,BF5E,F6E,E6E,DF6E,F5E,C6E,BF5E
//                                    04f,020 / 047,020 / 04e,020 / 04d,020 /
//                                    04a,020 / 042,020 / 049,020 / 047,020
//
// The driver adds OKEY only to SOUNDFUL notes — SNDPM.MAC's POKNL does
// `BEQ 9$ ;?SOUNDFUL NOTE?(NOT A REST)` BEFORE `ADDB OKEY(U)` — so the opening
// rest stays 0 while every pitch rides an octave up.
describe('sw7-8 — ORACLE: the finale (END) — the victory tune, transposed +12, rests intact', () => {
  const KEY = 12 // .NKEY 12. — DECIMAL (the dot); hex 0x12 would be +18
  const ENDV1_ORACLE = [
    [0x00, 0x80], // R1H — the rest does NOT take the key
    [0x4f + KEY, 0x20], // GF6E
    [0x47 + KEY, 0x20], // BF5E
    [0x4e + KEY, 0x20], // F6E
    [0x4d + KEY, 0x20], // E6E
    [0x4a + KEY, 0x20], // DF6E
    [0x42 + KEY, 0x20], // F5E
    [0x49 + KEY, 0x20], // C6E
    [0x47 + KEY, 0x20], // BF5E
  ]

  it('voice 1 opens with a silent rest, then the run — an octave above the written notes', () => {
    const v1 = decodeVoice(segOf('finale').voices[0])
    const got = v1.notes.slice(0, ENDV1_ORACLE.length).map((n) => [n.note, n.duration])
    expect(got).toEqual(ENDV1_ORACLE)
  })

  it('the key is +12, not the hex misreading +18', () => {
    const v1 = decodeVoice(segOf('finale').voices[0])
    expect(v1.notes[1].note).toBe(0x4f + 12)
    expect(v1.notes[1].note).not.toBe(0x4f + 0x12)
  })
})

// ── ORACLE 5: the descent — a straight stream, the rising line ───────────────
//
//   DESV1: ;.NRATE 80.  ;.AENV 2  ;.NVOL MP
//          ;.NOTE G5C,FS5C,E5D,A5QT,A5C,G5C,FS5D,B5QT
//          ;.NOTE B5C,A5C,G5D,C6C,B5C,A5D,E6C,D6C,C6D,FS6C,E6C,D6D
describe('sw7-8 — ORACLE: the descent (DES) — into the Death Star, note-for-note', () => {
  const DESV1_ORACLE = [
    [0x44, 0x16], // G5C
    [0x43, 0x16], // FS5C
    [0x41, 0x14], // E5D
    [0x46, 0x40], // A5QT
    [0x46, 0x17], // A5C (tied)
    [0x44, 0x16], // G5C
    [0x43, 0x14], // FS5D
    [0x48, 0x40], // B5QT
    [0x48, 0x17], // B5C (tied)
    [0x46, 0x16], // A5C
    [0x44, 0x14], // G5D
    [0x49, 0x16], // C6C
    [0x48, 0x16], // B5C
    [0x46, 0x14], // A5D
    [0x4d, 0x16], // E6C
    [0x4b, 0x16], // D6C
    [0x49, 0x14], // C6D
    [0x4f, 0x16], // FS6C
    [0x4d, 0x16], // E6C
    [0x4b, 0x14], // D6D
  ]

  it('voice 1 opens exactly as written', () => {
    const v1 = decodeVoice(segOf('descent').voices[0])
    const got = v1.notes.slice(0, DESV1_ORACLE.length).map((n) => [n.note, n.duration])
    expect(got).toEqual(DESV1_ORACLE)
  })

  it('.NRATE 80. is decimal 80', () => {
    const v1 = decodeVoice(segOf('descent').voices[0])
    expect(v1.tempo).toBe(80)
    expect(v1.tempo).not.toBe(0x80)
  })
})
